
[versions]
log4j = "1.2.17"
log4j2 = "2.25.1"

[libraries]
json-api = { module = "jakarta.json:jakarta.json-api", version = "2.1.3" }
json-impl = { module = "org.eclipse.parsson:parsson", version = "1.1.7" }
log4j = { module = "log4j:log4j", version.ref = "log4j" }
log4j2-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2" }
log4j2-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }

[bundles]
log4j2 = ["log4j2-api", "log4j2-core"]
